enum OrderBy { DATE, PRICE }

// 0000

const VENDOR_TYPE_PARTICULAR = 1 << 0; // 00001
const VENDOR_TYPE_PROFESSIONAL = 1 << 1; // 0010

// VENDOR_TYPE_PARTICULAR | VENDOR_TYPE_PROFESSIONAL 0011 (Ou logico BitFlag Rotacao de bit)
